import './globals.css';
import Footer from "@/components/Footer";
import Navber from "@/components/Navber";


export const metadata = {
  title: " Idea To Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navber />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
